export const GET_DESCR_REQUEST = 'GET_DESCR_REQUEST'
export const GET_DESCR_SUCCESS = 'GET_DESCR_SUCCESS'
export const GET_RECOM_REQUEST = 'GET_RECOM_REQUEST'
export const GET_RECOM_SUCCESS = 'GET_RECOM_SUCCESS'
